spring:
  application:
    name: professor-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
          jwk-set-uri: http://auth-server:9000/oauth2/jwks
      client:
        registration:
          ikub-client:
            provider: spring
            client-id: ikub
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          spring:
            issuer-uri: http://auth-server:9000
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true
server:
  port: 8083

resource:
  courseService:
    baseUrl: http://course-service:8087/course
  studentService:
    baseUrl: http://localhost:8084/student